# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            DSSG Peer Support
tagline:          ''
description:      'A 2019 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://uwescience.github.io"
baseurl:          "/DSSG-Peer-Support"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/DSSG-Peer-Support/
